version: '3.9'

services:
  app:
    image: node:18
    container_name: ecommerce_api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=ecommerce_user
      - DB_PASSWORD=ecommerce_pass
      - DB_DATABASE=ecommerce_db
    command: bash -c "npm install && npm run start:dev"

  postgres:
    image: postgres
    container_name: postgres_ecommerce
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
      POSTGRES_DB: ecommerce_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/ecommerce_dump.sql:/docker-entrypoint-initdb.d/ecommerce_dump.sql

volumes:
  postgres_data: